# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'api.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from add_key import Ui_Form as Ui_Form_add
from database.db import data_get, key_delete, data_update
from data.query import get_key
import threading


def data_num():
    data = data_get()
    i = 0
    for item in data:
        i += 1
    return i


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(750, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 3, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(data_num())
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 4)
        self.pushButton_2.clicked.connect(self.add_key_window)
        self.tableWidget.setColumnWidth(0, 400)

        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)

        # self.tableWidget.resizeColumnsToContents()
        self.tableWidget.resizeRowsToContents()
        self.tableWidget.verticalHeader().setVisible(False)
        # self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.setShowGrid(False)
        self.pushButton_2.clicked.connect(self.add_key_window)
        self.pushButton_2.clicked.connect(Form.close)
        self.pushButton_3.clicked.connect(self.data_delete)
        self.pushButton_4.clicked.connect(self.data_update)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.data_run()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "API Key 管理"))
        self.pushButton_3.setText(_translate("Form", "删除"))
        self.pushButton_4.setText(_translate("Form", "刷新"))
        self.pushButton_2.setText(_translate("Form", "添加"))
        self.pushButton_5.setText(_translate("Form", "历史"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Key"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "总量"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "已用"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "剩余"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)

    def add_key_window(self):
        self.form4 = QtWidgets.QWidget()
        self.ui4 = Ui_Form_add()
        self.ui4.setupUi(self.form4)
        self.form4.show()

    def data_run(self):
        data = data_get()
        number = 0
        for da123 in data:
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setVerticalHeaderItem(number, item)
            _translate = QtCore.QCoreApplication.translate
            item = self.tableWidget.verticalHeaderItem(number)
            item.setText(_translate("Form", "1"))
            number_2 = 0
            for i in da123:
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setItem(number, number_2, item)
                item = self.tableWidget.item(number, number_2)
                _translate = QtCore.QCoreApplication.translate
                item.setText(_translate("Form", str(i)))
                number_2 += 1
            number += 1

    def data_delete(self):
        selected_row = self.tableWidget.currentRow()
        item = self.tableWidget.item(selected_row, 0)
        if item is not None:
            data = item.text()
        key_delete(data)
        self.tableWidget.clearContents()
        self.tableWidget.setRowCount(data_num())
        self.data_run()

    def data_update(self):
        def _slot1(tableWidget, data_run):
            selected_row = tableWidget.currentRow()
            item = tableWidget.item(selected_row, 0)
            output = [0, 0]
            if item is not None:
                data = item.text()
            try:
                output = get_key(data)
            except:
                print("查询失败")
            total = output[0]
            usage = output[1]
            usage = round(usage, 6)
            rest = total - usage
            data_update(total, usage, rest, data)
            data_run()

        threading.Thread(target=_slot1, args=(self.tableWidget, self.data_run)).start()
